[project]
name = "sphinx_shiguredo_theme"
authors = [{ name = "Shiguredo Inc." }]
version = "2025.1.0"
description = "Sphinx Shiguredo Theme"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">= 3.11"

[project.urls]
Source = "https://github.com/shiguredo/sphinx_shiguredo_theme"
Discord = "https://discord.gg/shiguredo"


[build-system]
requires = ["setuptools>=80.9", "wheel>=0.45.1"]

[tool.rye]
dev-dependencies = ["ruff", "ty"]

[tool.ruff]
target-version = "py311"
line-length = 100
